### ISSUE TITLE
New migration of SolarSchedule is always made when run `makemigrations`

### ISSUE THREAD

**Issue by MidTin** [celery/django-celery-beat#100]
It seems the choices of SolarSchedule.event make this happen.

https://github.com/celery/django-celery-beat/blob/master/django_celery_beat/models.py#L43

**Comment by thedrow** [comment]
Thanks.
We'll fix this before a new release :)

**Comment by paultiplady** [comment]
@thedrow any idea roughly when the next release will be (days/weeks/months)? Just trying to figure out if it's worth it to fork the repo and carry this fix in the meantime, but don't think I'll bother if you have concrete plans to do a release imminently. Thanks!

**Comment by thedrow** [comment]
I'll need to find the fix for the problem first.

**Comment by paultiplady** [comment]
Doesn't https://github.com/celery/django-celery-beat/pull/92 fix this?

(Looks like this issue is dupe'd with #92 and #91)

**Comment by thedrow** [comment]
Fixed.

**Comment by ACPK** [comment]
@MidTin - I noticed this was closed but there hasn't been a new version (still on 1.1.0). Will a new version be created?

**Comment by fuatu** [comment]
I still have  the same problem. I have version 1.1.0.
each makemigration gives an output of:
Alter field event on solarschedule

I think the issue is not fixed
