### ISSUE TITLE
Interval tasks not running

### ISSUE THREAD

**Issue by jackylvm** [celery/django-celery-beat#299]
### Summary:
I have an interval and clocked beat. If clocked has expired (e.g. today is January 9th and clocked is January 8th), my interval will not run again.

* Celery Version: 4.4.0
* Celery-Beat Version: 1.5.0

### Exact steps to reproduce the issue:
1. Add an interval task like 5 seconds
2. Add a clocked task
3. run celery beat 'celery -A mercury beat -l debug'

### Detailed information

The clocked 'is_due' function returns (False, None), causing the Scheduler variable _heap to never change. Because _heap is a small top heap and is based on 'event_t = namedtuple (' event_t ', (' time ' , 'priority', 'entry')) 'sorted by' time ', clocked is always the smallest one, always at the top of the heap.

**Comment by auvipy** [comment]
I think its already fixed with a newer release

**Comment by lopes05** [comment]
Tried this with v2.2.0, problem still occurs.

Whenever I change DatabaseSchedule, adding a new clockedTask , interval tasks just stop running, until I restart my celery beat. Clocked tasks still works
