### ISSUE TITLE
AttributeError 'cached_property' object has no attribute 'lock'

### ISSUE THREAD

**Issue by timur-ul-hasan** [celery/django-celery-beat#684]
### Summary:

* Celery Version: 5.3.4
* Celery-Beat Version: 2.5.0

### Exact steps to reproduce the issue:
1. Using the above version combination celery-beat doesn't start throw error.

### Detailed information

Please include more detailed information here, such as relevant information about your system setup, things you did to try and debug the problem, log messages, etc.  
<img width="1047" alt="image" src="https://github.com/celery/django-celery-beat/assets/18367278/d16ed785-ec2a-4154-baf4-2b3657dc53f5">

**Comment by auvipy** [comment]
are you using python 3.12?

**Comment by cclauss** [comment]
Is this fixed in release [`v2.6.0`](https://github.com/celery/django-celery-beat/releases) which supports Python 3.12?

**Comment by MarshallEriksen-shaomingyang** [comment]
Had this issue fixed in latest release?

**Comment by mboker** [comment]
I am using python 3.12.4 and django-celery-beat 2.6.0 and still seeing this issue. I can't tell if it is impacting anything, but I am seeing it in my logs at startup.
